name: Deploy Second Game

on:
  push:
    branches: [ master ] 

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t keep-white-space:latest .

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # On déploie la racine car index.html est ici
          branch: gh-pages